{"uuid": "f7a428c2-55fe-40cc-b9b6-bc420ec44d83", "children": ["788f7801-1752-4bfe-a7b8-9c3792dd3138"], "befores": [{"name": "create_driver", "status": "passed", "start": 1675060547171, "stop": 1675060550454}], "afters": [{"name": "create_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=109.0.5414.119)\nStacktrace:\n0   chromedriver                        0x0000000102b430fc chromedriver + 4223228\n1   chromedriver                        0x0000000102acb284 chromedriver + 3732100\n2   chromedriver                        0x000000010277f5c8 chromedriver + 275912\n3   chromedriver                        0x00000001027597b0 chromedriver + 120752\n4   chromedriver                        0x00000001027e00f8 chromedriver + 671992\n5   chromedriver                        0x00000001027f2b18 chromedriver + 748312\n6   chromedriver                        0x00000001027ad748 chromedriver + 464712\n7   chromedriver                        0x00000001027ae7f0 chromedriver + 468976\n8   chromedriver                        0x0000000102b13e08 chromedriver + 4029960\n9   chromedriver                        0x0000000102b17698 chromedriver + 4044440\n10  chromedriver                        0x0000000102b17cc0 chromedriver + 4046016\n11  chromedriver                        0x0000000102b1e4c4 chromedriver + 4072644\n12  chromedriver                        0x0000000102b1836c chromedriver + 4047724\n13  chromedriver                        0x0000000102af0bd8 chromedriver + 3886040\n14  chromedriver                        0x0000000102b34efc chromedriver + 4165372\n15  chromedriver                        0x0000000102b35050 chromedriver + 4165712\n16  chromedriver                        0x0000000102b49e20 chromedriver + 4251168\n17  libsystem_pthread.dylib             0x0000000189a5d06c _pthread_start + 148\n18  libsystem_pthread.dylib             0x0000000189a57e2c thread_start + 8\n\n", "trace": "  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/razvan/Work/qa_manga_web/web_tests/conftest.py\", line 118, in create_driver\n    allure.attach(body=driver.get_screenshot_as_png(), name=screenshot_name,\n  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 926, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 937, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/razvan/Work/qa_manga_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1675060551400, "stop": 1675060551401}], "start": 1675060547171, "stop": 1675060551401}